# Project configuration.
project:
    name: test_mock

package:
    remote: master

    remotes:
        master:
            backend: mock
            dir: mock/backend_root
            upload_dir: /tmp/bazel_external_data/upload
