# Example user configuration for private authentication bits.
# The updated version of this file should live in ~/.config/external_data_bazel/config.yml
core:
    # Where cache files are stored, if the project does not have its own specific cache store.
    #   Storage: {cache_dir}/{hash_type}/{hash[0:2]}/{hash[2:4]}/{hash}
    cache_dir: ~/.cache/external_data_bazel/

# Girder Backend settings.
girder:
    url:
        "https://girder.example.com":
            # Authentication. Leave empty if no authentication needed.
            "api_key": "<insert api key here>",
