#!/bin/bash
set -e -u

# Proxy to use Bazel binary, but access to PWD.

workspace_dir=$(cd $(dirname $0)/.. && pwd)
bin_dir=${workspace_dir}/bazel-bin/external/external_data_bazel_pkg/src/external_data_bazel
bin=${bin_dir}/cli

extra_args=--user_config=${workspace_dir}/tools/external_data.user.yml

do_build=
if [[ $# -gt 0 && $1 == --do_build ]]; then
    do_build=1
    shift
fi

if [[ ! -f ${bin} || -n $do_build ]]; then
    bazel build @external_data_bazel_pkg//:cli
fi

echo "cmd: ${bin} ${extra_args} $@" | \
    sed \
        -e "s#${bin_dir}#\${bin_dir}#g" \
        -e "s#${workspace_dir}#\${workspace_dir}#g"
${bin} ${extra_args} "$@"
