#!/bin/bash
set -e -u

# Proxy to use Bazel binary, but access to PWD.
workspace_dir=$(cd $(dirname $0)/.. && pwd)
bin_dir=${workspace_dir}/bazel-bin/external/external_data_bazel_pkg
bin=${bin_dir}/cli
# Build the binary if it does not exist.
if [[ ! -f ${bin} ]]; then
    bazel build @external_data_bazel_pkg//:cli
fi
# Execute.
${bin} "$@"
