workspace(name = "bazel_external_data_pilot")

load("//tools:path.bzl", "dirname")

local_repository(
    name = "bazel_external_data_pkg",
    path = dirname(dirname(dirname(dirname(__workspace_dir__)))),
)
