workspace(name = "test_simple_downstream")

load("//:path.bzl", "dirname")

# <workspace_import name="test_simple">
local_repository(
    name = "external_data_bazel_pkg",
    path = dirname(dirname(__workspace_dir__)),
)
# </workspace_import>  <!-- test_simple -->

local_repository(
    name = "test_simple",
    path = dirname(__workspace_dir__) + "/test_simple",
)
